baseURL = "https://jimducker.nl"
languageCode = "en-US"
title = "Jim D端cker"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
theme = "hugo-sustain"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5


[permalinks]
  post = "/:day/:month/:year/:slug"

[params]
  avatar = "img/profile2.png"
  author = "Jim D端cker"
  description = "Hi, I'm Jim D端cker. Welcome to my portfolio website!"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "jimduckernl"
  Email         = "jim@soverin.net"
  LinkedIn      = "jim-d端cker-596541221"

## Main Menu
[[menu.main]]
  name = "about me"
  weight = 100
  identifier = "aboutme"
  url = "/about/"
#[[menu.main]]
#  name = "skills"
#  identifier = "skills"
#  weight = 200
#  url = "/skills/"
[[menu.main]]
  name = "experience"
  identifier = "experience"
  weight = 200
  url = "/experience/"
